[theme]
base = "dark"
primaryColor = "#35c4d5"
backgroundColor = "#0d1114"
secondaryBackgroundColor = "#20262e"
textColor = "#f7f3ec"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
