# Generated by Django 5.2.16 on 2026-07-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=9, unique=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=128)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.CharField(default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('highest_role', models.CharField(choices=[('pi', 'PI'), ('budget_manager', 'Budget Manager'), ('lead', 'Team Leader'), ('member', 'Member')], default='member', max_length=32)),
                ('team_names', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_email', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('parsed_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('review', 'Needs review'), ('ready', 'Ready'), ('dismissed', 'Dismissed')], default='review', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('uploader_email', 'file_sha256'), name='unique_user_pdf')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('matched', 'Matched'), ('mismatch', 'Mismatch'), ('failed', 'Failed')], default='running', max_length=16)),
                ('actor', models.CharField(blank=True, max_length=160)),
                ('source_transaction_count', models.PositiveIntegerField(default=0)),
                ('mirror_transaction_count', models.PositiveIntegerField(default=0)),
                ('source_totals', models.JSONField(blank=True, default=dict)),
                ('mirror_totals', models.JSONField(blank=True, default=dict)),
                ('differences', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='budget.fiscalyear')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('budget_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.fiscalyear')),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'category'), name='unique_fy_category')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('allocation_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('manager_emails', models.JSONField(blank=True, default=list)),
                ('lead_emails', models.JSONField(blank=True, default=list)),
                ('member_emails', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='budget.fiscalyear')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'name'), name='unique_fy_team')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('po_number', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_usd_equiv', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(default='Allocated', max_length=32)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('entered_by', models.EmailField(blank=True, max_length=254)),
                ('entry_method', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('pdf_link', models.URLField(blank=True, max_length=1000)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.fiscalyear')),
            ],
            options={
                'ordering': ['-date', '-transaction_id'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'transaction_id'), name='unique_fy_transaction')],
            },
        ),
    ]
