# Generated by Django 5.2.16 on 2026-07-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_invoicedraft_import_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedraft',
            name='content_type',
            field=models.CharField(default='application/pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicedraft',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_drafts', to='budget.fiscalyear'),
        ),
        migrations.AddField(
            model_name='invoicedraft',
            name='object_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='invoicedraft',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedraft',
            name='team',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sheet_last_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicedraft',
            name='status',
            field=models.CharField(choices=[('review', 'Needs review'), ('ready', 'Ready'), ('processing', 'Processing'), ('imported', 'Imported'), ('dismissed', 'Dismissed')], default='review', max_length=16),
        ),
        migrations.CreateModel(
            name='SheetOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('operation_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('actor', models.EmailField(blank=True, max_length=254)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheet_operations', to='budget.fiscalyear')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_operations', to='budget.transaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='budget_shee_status_d04a20_idx'), models.Index(fields=['operation_type', 'created_at'], name='budget_shee_operati_a82ff1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='budget.transaction')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['transaction', '-timestamp'], name='budget_tran_transac_7ded6e_idx')],
            },
        ),
    ]
