# Generated by Django 5.2.16 on 2026-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_invoicedraft_content_type_invoicedraft_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='aed_per_usd',
            field=models.DecimalField(decimal_places=6, default=3.6725, max_digits=12),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='exchange_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
