# Generated by Django 5.2.16 on 2026-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_fiscalyear_aed_per_usd_fiscalyear_exchange_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='team_roles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
