# Generated by Django 5.2.16 on 2026-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_labmember_team_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='budget_admi_action_964c3c_idx')],
            },
        ),
    ]
