# Generated by Django 5.2.16 on 2026-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=160, unique=True)),
                ('record_type', models.CharField(choices=[('protocol', 'Protocol'), ('notebook', 'Notebook')], max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('team', models.CharField(blank=True, max_length=240)),
                ('owner', models.CharField(blank=True, max_length=240)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('source_path', models.CharField(blank=True, max_length=1200)),
                ('object_name', models.CharField(blank=True, max_length=1200)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'record_id'],
                'indexes': [models.Index(fields=['record_type', 'team'], name='labapps_kno_record__fc48c3_idx'), models.Index(fields=['record_type', 'status'], name='labapps_kno_record__8b0f8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabAppAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.EmailField(blank=True, max_length=254)),
                ('app_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=80)),
                ('target', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['app_id', '-timestamp'], name='labapps_lab_app_id_127cf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SheetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('registry', 'Registry'), ('tracker', 'Project tracker')], max_length=24)),
                ('table_name', models.CharField(max_length=64)),
                ('record_id', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'table_name', 'record_id'],
                'indexes': [models.Index(fields=['source', 'table_name'], name='labapps_she_source_7cd158_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'table_name', 'record_id'), name='unique_lab_sheet_record')],
            },
        ),
    ]
