# Generated by Django 5.2.16 on 2026-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapps', '0002_knowledge_catalog_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_email', models.EmailField(max_length=254, unique=True)),
                ('slack_team_id', models.CharField(max_length=32)),
                ('slack_team_name', models.CharField(max_length=160)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('slack_user_name', models.CharField(max_length=160)),
                ('slack_email', models.EmailField(blank=True, max_length=254)),
                ('access_token_ciphertext', models.TextField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('confirmed', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['portal_email'],
                'indexes': [models.Index(fields=['slack_team_id', 'slack_user_id'], name='labapps_sla_slack_t_0a2ac7_idx')],
            },
        ),
    ]
